---

- name: install fail2ban for Debian
  apt: pkg=fail2ban state={{ fail2ban_pkg_state }}
  when: ansible_os_family == 'Debian'
  tags: [fail2ban]

- name: install fail2ban for RedHat
  yum: name=fail2ban state={{ fail2ban_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: [fail2ban]

- name: update configuration file - /etc/fail2ban/fail2ban.conf
  template:
    src: etc/fail2ban/fail2ban.conf.j2
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]

- name: Fail2ban | Add fail2ban jails
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local backup=yes mode=0644
  tags: [fail2ban]
  notify:
    - restart fail2ban

- name: Fail2ban | Add fail2ban filters
  copy: src={{ item }} dest=/etc/fail2ban/filter.d/{{ item }}
  with_items:
    - apache-myadmin.conf
    - apache-w00tw00t.conf
  tags: [fail2ban]

- name: Fail2ban | Ensure fail2Ban restarts after system restart
  lineinfile:
            dest=/etc/default/fail2ban
            regexp='FAIL2BAN_OPTS='
            line='FAIL2BAN_OPTS="-x"'
            state=present
  tags: [fail2ban]
  notify:
   - restart fail2ban

- name: start/stop fail2ban service
  service: name=fail2ban state={{ fail2ban_service_state }} enabled={{ fail2ban_service_enabled }}
  tags: service