---
- name: Converge
  hosts: all
  become: true

  vars:
    fail2ban_debug: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=1200
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-f5-fail2ban
